@startuml

top to bottom direction
skinparam dpi 50
skinparam linetype ortho

package "Browser" {
	[Web browser] as browser #LemonChiffon
	[HTML] as html #Gold
	[JavaScript] as js #Gold
	[CSS] as css #Gold
}

package "Frontend" {
	package "Forms" {
		[Login form] as login_form #Khaki
		[Registration form] as registration_form #Khaki
		[Profile management form] as profile_form #Khaki
		[Fuel quote form] as quote_form #Khaki
		[Fuel quote history] as quote_history #Khaki
	}
}

package "Backend" {
	[Rust API backend] as backend #Chocolate

	package "Components" {
		[Authentication manager] as auth_manager #Salmon
		[Profile manager] as profile_manager #Salmon
		[Pricing module] as pricing_module #Salmon
	}
}

package "Database" {
	[SQLite RDBMS] as database #Aquamarine
}

registration_form -> login_form
login_form -> profile_form
login_form -> quote_form
quote_form <--> quote_history

Browser -d-> Frontend
Frontend -d-> backend

html -u-> browser
css -u-> browser
js <-u-> browser


backend -d-> database
backend <--> auth_manager
backend <--> profile_manager
backend <--> pricing_module

'login_form -d-> auth_manager
'registration_form -d-> auth_manager
'profile_form -d-> profile_manager
'quote_form -d-> pricing_module
'quote_history -d-> pricing_module

@enduml
