name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run unit tests & generate code coverage
        run: |
          cd src/backend
          echo 'database_uri = "sqlite://:memory:"\nmax_connections=1" > config.toml' # use in-memory database
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
